spring.datasource.url=jdbc:mysql://tramway.proxy.rlwy.net:52942/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=KRrkXnBJOqQpAIJlzumsNjMoMfjFcTDU
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}