spring.datasource.url=jdbc:postgresql://dpg-d81pmlreo5us73afplcg-a.oregon-postgres.render.com:5432/taskmanagerdb_bplp?sslmode=require
spring.datasource.username=taskmanagerdb_bplp_user
spring.datasource.password=3zMciQHBdUVWaeWzGtSvZQJILupuTRww
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}