spring.datasource.url=jdbc:postgresql://dpg-d81lekj7uimc738n989g-a:5432/taskmanagerdb_x03x
spring.datasource.username=taskmanagerdb_x03x_user
spring.datasource.password=IHPW2VKBgiFElzCX4TWNZo8Ijdg751kX
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}